### ISSUE TITLE
[Help] Button background에 NavigationLink를 넣으면 랜덤 선택되는 문제

### ISSUE THREAD

**Issue by sunshiningsoo** [DeveloperAcademy-POSTECH/CultureCenter-AppleMusicClone-DakeWill#14]
### Description
앨범리스트에서 앨범 선택을 할 때, Firebase로 저장시키고 싶어서 Button의 background로 NavigationLink를 넣어줬더니, 앨범 리스트 선택에서 랜덤으로 아무 앨범을 로드하는 문제(FirebaseSave 브랜치에 있음)

### To-do
- [x] 앨범리스트에서 선택한 앨범이 디테일뷰에서도 그대로 나오게 해야 한다.
- [x] HELP DAKE!

### etc
도움을 받은 링크
https://stackoverflow.com/a/63367285/19350352

**Comment by ccdkk** [comment]
아 이거 저도 예전에 애먹고 해결 못했었는데
https://stackoverflow.com/questions/64756332/swiftui-navigationlink-in-lazyvgrid-picking-random-index
요거 한 번 참고해보실래요?? 
navigation에 tag , selection을 넣을 수 있네요..?

**Comment by ccdkk** [comment]
이거 해결한 코드 올렸습니다.

**Comment by sunshiningsoo** [comment]
데이크 최고👍
